#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_env="0.0.1"
  jq -n --arg fogg_env "$ver_fogg_env" '{fogg_env: $fogg_env}'
}

version "$@"
